spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

firebase:
  service-account:
    path: C:\Users\educh\OneDrive\Área de Trabalho\hermes-api-repository\src\main\resources\API-firebase.json

server:
  port: 8090
  # Configurações para habilitar o GZIP nas responses da API
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
  servlet:
    context-path: /api